// www-workspace/spa/src/app/components/pages/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../services';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html'
})
export class LoginComponent{

    constructor(
        private router: Router,
        private authService: AuthService
    ) { }

    private loginEmail: string = '';
    private loginPassword: string = '';

    private bAttemptingLogin: boolean = false;
    private bLoginFailed: boolean = false;

    private error = '';

    onSubmit(f) {

        this.bAttemptingLogin = true;
        this.bLoginFailed = false;
        this.error = '';

        this.authService.attemptLogin(this.loginEmail, this.loginPassword)
            .subscribe(
                result => {
                    this.bAttemptingLogin = false;
                    if (result.success === true) {
                        // login successful
                        this.router.navigate(['/' + result.user]);
                    } else {
                        this.bLoginFailed = true;
                        
                        this.error = 'Email or password is incorrect';
                    }
                },
                err => {
                    this.bAttemptingLogin = false;
                }
            );
      }

}

<app-header [bEmpty]="true"></app-header>

<div class="ui middle aligned center aligned grid">
    <div class="middle-form-column">
        <h2 class="ui header">
            <div class="content">
                Login
            </div>
        </h2>
        <form
            class="ui large form"
            (ngSubmit)="onSubmit(f)"
            #f="ngForm"
        >
            <div *ngIf="bLoginFailed" class="ui red segment">
                <strong>{{error}}</strong>
            </div>

            <div class="ui stacked segment" [ngClass]="{'loading': bAttemptingLogin}">
                <div class="field" [ngClass]="{'error': bLoginFailed}">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input
                        type="text"
                        name="email"
                        placeholder="E-mail address"
                        [(ngModel)]="loginEmail"
                        >
                    </div>
                </div>
                <div class="field" [ngClass]="{'error': bLoginFailed}">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input
                            type="password"
                            name="password"
                            placeholder="Password"
                            [(ngModel)]="loginPassword"
                        >
                    </div>
                </div>

                <!-- disabled if we are awaiting login request response OR unless they are both filled in -->
                <button [disabled]="bAttemptingLogin || !(loginEmail !== '' && loginPassword !== '')" type="submit" class="ui fluid large button primary submit">Login</button>
            </div>

        </form>

        <div class="">
            or <a class="picili-link" [routerLink]="['/register']">register</a>
        </div>
    </div>
</div>

// frontend/client/src/components/Login.tsx
import * as React from 'react'
import * as ReactRedux from 'react-redux'
import { useMutation, gql } from '@apollo/client'
import classNames from 'classnames'
import { NavLink } from 'react-router-dom'

import * as Actions from 'src/redux/actions'

const loginQuery = gql`
	mutation login($authInput: LoginInput!) {
		login(authInput: $authInput) {
			token
			error
		}
	}
`

const Login: React.FunctionComponent = () => {
	const [email, setEmail] = React.useState<string>('')
	const [password, setPassword] = React.useState<string>('')
	const [error, setError] = React.useState<string>('')

	const [loginMutation, { error: httpError, data, loading = false }] =
		useMutation(loginQuery)

	const dispatch = ReactRedux.useDispatch()

	React.useEffect(() => {
		if (data?.login.token) {
			dispatch(Actions.attemptLoginSucceeded(data.login.token))
		}
		if (data?.login.error) {
			setError(data.login.error)
		}
	}, [data])

	const loginHandler = async (e: React.FormEvent) => {
		e.preventDefault()
		await loginMutation({ variables: { authInput: { email, password } } })
	}

	const loginFailed = httpError?.message || data?.login.error || error
	const formDisabled = loading || !(email !== '' && password !== '')

	return (
		<React.Fragment>
			<div className="ui middle aligned center aligned grid">
				<div className="middle-form-column">
					<h2 className="ui header">
						<div className="content">Login</div>
					</h2>

					<form onSubmit={loginHandler} className="ui large form">
						{loginFailed && (
							<div className="ui red segment">
								<strong>{loginFailed}</strong>
							</div>
						)}

						<div
							className={classNames({
								'ui stacked segment': true,
								loading: loading,
							})}
						>
							<div
								className={classNames({
									field: true,
									error: loginFailed,
								})}
							>
								<div className="ui left icon input">
									<i className="user icon"></i>

									<input
										type="text"
										value={email}
										onChange={(e) =>
											setEmail(e.target.value)
										}
										disabled={loading}
										placeholder="email"
									/>
								</div>
							</div>

							<div
								className={classNames({
									field: true,
									error: loginFailed,
								})}
							>
								<div className="ui left icon input">
									<i className="lock icon"></i>

									<input
										type="password"
										value={password}
										onChange={(e) =>
											setPassword(e.target.value)
										}
										disabled={loading}
										placeholder="password"
									/>
								</div>
							</div>

							<button
								type="submit"
								disabled={formDisabled}
								className="ui fluid large button primary submit"
							>
								Login
							</button>
						</div>
					</form>

					<div>
						or{' '}
						<NavLink
							exact={true}
							className="picili-link"
							to="/register"
						>
							register
						</NavLink>
					</div>
				</div>
			</div>
		</React.Fragment>
	)
}

export default Login
