// www-workspace/spa/src/app/components/pages/register/register.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../services';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html'
})
export class RegisterComponent {

    constructor(
        private router: Router,
        private authService: AuthService
    ) { }

    private registerUsername: string = '';
    private registerEmail: string = '';
    private registerPassword: string = '';

    private bAttemptingRegister: boolean = false;

    private errors: string[] = [];
    private bRegisterFailed: boolean = false;

    onRegisterSubmit(frmRegister) {

      this.bAttemptingRegister = true;
      this.bRegisterFailed = false;
      this.errors = [];

      this.authService.attemptRegister(
          this.registerEmail,
          this.registerPassword
      )
          .subscribe(
              result => {
                  this.bAttemptingRegister = false;
                  if (result.successful === true) {
                      // register successful
                      this.bRegisterFailed = false;
                      this.errors = [];
                      this.router.navigate(['/' + result.user]);
                  }else{
                      this.bRegisterFailed = true;
                      this.errors = result.errors;
                  }
              }
          );
    }

}


<div class="ui middle aligned center aligned grid">
    <div class="middle-form-column">
        <h2 class="ui header">
            <div class="content">
                Register
            </div>
        </h2>
        <form
            class="ui large form"
            (ngSubmit)="onRegisterSubmit(frmRegister)"
            #frmRegister="ngForm"
        >
            <div *ngIf="bRegisterFailed" class="ui red segment">
                <strong>{{errors.join(', ')}}</strong>
            </div>

            <div class="ui stacked segment" [ngClass]="{'loading': bAttemptingRegister}">

                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input
                        type="text"
                        name="email"
                        placeholder="Email"
                        [(ngModel)]="registerEmail"
                        >
                    </div>
                </div>

                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input
                            type="password"
                            name="password"
                            placeholder="Password"
                            [(ngModel)]="registerPassword"
                        >
                    </div>
                </div>

                <button [disabled]="bAttemptingRegister" type="submit" class="ui fluid large button primary submit">Register</button>
            </div>

            <div *ngIf="errors.length > 0" class="ui error message">
                <ul>
                    <li *ngFor="let error of errors">{{error}}</li>
                </ul>
            </div>

        </form>

        <div class="">
            or <a class="picili-link" [routerLink]="['/login']">login</a>
        </div>
    </div>
</div>

// frontend/client/src/components/Register.tsx
import * as React from 'react'
import * as ReactRedux from 'react-redux'
import { useMutation, gql } from '@apollo/client'
import { NavLink } from 'react-router-dom'
import classNames from 'classnames'
import * as Actions from 'src/redux/actions'

const registerQuery = gql`
	mutation register($authInput: RegisterInput!) {
		register(authInput: $authInput) {
			token
			error
		}
	}
`

const Register: React.FunctionComponent = () => {
	const [email, setEmail] = React.useState<string>('')
	const [password, setPassword] = React.useState<string>('')
	const [passwordConfirmation, setPasswordConfirmation] =
		React.useState<string>('')
	const [error, setError] = React.useState<string>('')

	const [registerMutation, { error: httpError, data, loading = false }] =
		useMutation(registerQuery)

	const dispatch = ReactRedux.useDispatch()

	React.useEffect(() => {
		if (data?.register.token) {
			dispatch(Actions.attemptLoginSucceeded(data.register.token))
		}
		if (data?.register.error) {
			setError(data.register.error)
		}
	}, [data])

	const registerHandler = async (e: React.FormEvent) => {
		e.preventDefault()
		await registerMutation({
			variables: { authInput: { email, password, passwordConfirmation } },
		})
	}

	const registrationFailed =
		httpError?.message || data?.register.error || error
	const formDisabled =
		loading ||
		!(email !== '' && password !== '' && passwordConfirmation !== '')

	return (
		<React.Fragment>
			<div className="ui middle aligned center aligned grid">
				<div className="middle-form-column">
					<h2 className="ui header">
						<div className="content">Register</div>
					</h2>

					<form onSubmit={registerHandler} className="ui large form">
						{registrationFailed && (
							<div className="ui red segment">
								<strong>{registrationFailed}</strong>
							</div>
						)}

						<div
							className={classNames({
								'ui stacked segment': true,
								loading: loading,
							})}
						>
							<div
								className={classNames({
									field: true,
									error: registrationFailed,
								})}
							>
								<div className="ui left icon input">
									<i className="user icon"></i>

									<input
										type="text"
										value={email}
										onChange={(e) =>
											setEmail(e.target.value)
										}
										disabled={loading}
										placeholder="email"
									/>
								</div>
							</div>

							<div
								className={classNames({
									field: true,
									error: registrationFailed,
								})}
							>
								<div className="ui left icon input">
									<i className="lock icon"></i>

									<input
										type="password"
										value={password}
										onChange={(e) =>
											setPassword(e.target.value)
										}
										disabled={loading}
										placeholder="password"
									/>
								</div>
							</div>

							<div
								className={classNames({
									field: true,
									error: registrationFailed,
								})}
							>
								<div className="ui left icon input">
									<i className="lock icon"></i>

									<input
										type="password"
										value={passwordConfirmation}
										onChange={(e) =>
											setPasswordConfirmation(
												e.target.value,
											)
										}
										disabled={loading}
										placeholder="confirm password"
									/>
								</div>
							</div>

							<button
								type="submit"
								disabled={formDisabled}
								className="ui fluid large button primary submit"
							>
								Register
							</button>
						</div>
					</form>

					<div>
						or{' '}
						<NavLink
							exact={true}
							className="picili-link"
							to="/login"
						>
							login
						</NavLink>
					</div>
				</div>
			</div>
		</React.Fragment>
	)
}

export default Register
