// frontend/client/src/components/partials/Header.tsx
import * as React from 'react'
import * as ReactRedux from 'react-redux'
import { NavLink } from 'react-router-dom'

import * as Actions from 'src/redux/actions'
import * as Selectors from 'src/redux/selectors'

const Header: React.FunctionComponent = () => {
	const loadingSomething = false // searchService.bSearching || httpService.bMakingRequestToServer
	const isAuthenticated = ReactRedux.useSelector(
		Selectors.userIsAuthenticated,
	)

	const dispatch = ReactRedux.useDispatch()
	const logOut = () => dispatch(Actions.logout())

	return (
		<React.Fragment>
			{loadingSomething && (
				<div className="indeterminate-loading-bar progress">
					<div className="indeterminate"></div>
				</div>
			)}

			<div id="header">
				<span className="header-font">
					<NavLink exact={true} className="header-font" to="/">
						picili
					</NavLink>
				</span>

				<div id="top-right-links">
					{isAuthenticated && (
						<div>
							{/* <span
								id="processing-header-output"
								*ngIf="bProcessing"
								class="ui basic tiny label"
								title="{{cProcessingFiles | number}} file(s) to go, across {{cProcessingTasks | number}} task(s)"
							>
								<i class="fa fa-cogs"></i>&nbsp;
								Synchronising / Processing
							</span> */}

							<NavLink
								exact={true}
								className="ui tiny button"
								to="/admin"
							>
								<i className="fa fa-cog" aria-hidden="true"></i>
								&nbsp;settings
							</NavLink>

							<button className="ui tiny button" onClick={logOut}>
								<i className="fa fa-cog" aria-hidden="true"></i>
								&nbsp;logout
							</button>
						</div>
					)}
					{!isAuthenticated && (
						<div>
							<NavLink
								exact={true}
								className="ui tiny button"
								to="/login"
							>
								login
							</NavLink>

							<NavLink
								exact={true}
								className="ui tiny button"
								to="/register"
							>
								register
							</NavLink>
						</div>
					)}
				</div>
			</div>
		</React.Fragment>
	)
}

export default Header

// www-workspace/spa/src/app/components/shared/header/header.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AuthService, HttpService, SearchService } from './../../../services';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent{

    @Input() bEmpty: boolean = false;

    private sUsername: string = '';
    private bProcessing: boolean = false;
    private cProcessingTasks: number = 0;
    private cProcessingFiles: number = 0;

    private bAuthenticated: boolean = false;
    private bOnUserPage: boolean = false;
    private sCurrentPageUsername: string = 'giraffe';
    private bShowingUserDropdownMenu: boolean = false;

    constructor(
        private httpService: HttpService,
        private authService: AuthService,
        private searchService: SearchService,
        route: ActivatedRoute
    ) {
        this.sCurrentPageUsername = route.snapshot.params['username'];

        this.bOnUserPage = (typeof this.sCurrentPageUsername !== "undefined") ? true : false;

        this.bAuthenticated = this.authService.isLoggedIn();
        
        this.authService.authStatusChanged.subscribe(b => {
            this.bAuthenticated = b;
        });
    }

    ngOnInit() {
        /*
        3/6/17 - commented out so as now to make /me request on each page change, is it needed anywhere even?
        */

        // only call backend asking for username if we don't have it
        if (this.sUsername === '')
        {
            this.httpService.getUser().subscribe(
                (mData) => {
                    this.sUsername = mData.username;
                    this.bProcessing = mData.bProcessing;
                    this.cProcessingTasks = mData.cProcessing;
                    this.cProcessingFiles = mData.cFiles;
                },
                (err) => {
                    if (this.bAuthenticated) {
                        this.bAuthenticated = false;
                        this.authService.logOut();
                    }
                }
            );
        }
    }

    onLogout(){
        this.authService.logOut();
    }

}

<div class="indeterminate-loading-bar progress" *ngIf="searchService.bSearching || httpService.bMakingRequestToServer">
    <div class="indeterminate"></div>
</div>

<div id="header">

    <span class="header-font"><a [routerLink]="['/' + sUserId + '/']">picili</a></span>
    
    <div id="top-right-links">

        <!-- logged in -->
        <div *ngIf="bAuthenticated">
			<span
				id="processing-header-output"
				*ngIf="bProcessing"
				class="ui basic tiny label"
				title="{{cProcessingFiles | number}} file(s) to go, across {{cProcessingTasks | number}} task(s)"
			>
				<i class="fa fa-cogs"></i>&nbsp;
				Synchronising / Processing
			</span>
            
            <a *ngIf="sUsername !== ''" [routerLink]="['/' + sUserId + '/settings']" class="ui tiny button">
                <i class="fa fa-cog" aria-hidden="true"></i>&nbsp;settings
            </a>

            <a class="ui tiny button" (click)="onLogout()">logout</a>
        </div>
        <!-- not logged in - guest -->
        <div *ngIf="!bAuthenticated">
            <a class="ui tiny button" [routerLink]="['/login']">login</a>
            <a class="ui tiny button" [routerLink]="['/register']">register</a>
        </div>
    </div>
</div>
